change_amount = ""
change_commitment = ""
change_randomness = ""
input_0_amount = ""
input_0_leaf_index = ""
input_0_randomness = ""
input_0_siblings = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
input_1_amount = ""
input_1_leaf_index = ""
input_1_randomness = ""
input_1_siblings = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
intent_nullifier = ""
merkle_root = ""
nullifier_0 = ""
nullifier_1 = ""
nullifier_key = ""
pub_key_x = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
pub_key_y = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
signature = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
tx_gas_limit = ""
tx_max_fee = ""
tx_max_priority_fee = ""
tx_nonce = ""
withdraw_amount = ""
withdraw_recipient = ""
