[package]
name = "transfer"
type = "bin"
authors = [""]

[dependencies]
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }
common = { path = "../common" }
poseidon = { tag = "v0.2.0", git = "https://github.com/noir-lang/poseidon" }
