[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"

remappings = [
    "forge-std/=lib/forge-std/src/",
    "poseidon-solidity/=lib/poseidon-solidity/contracts/"
]

[fmt]
line_length = 100
tab_width = 4
